import sqlite3
from sqlite3.dbapi2 import Error
from config import DB_PATH

def create_connection():
    try:
        conn = sqlite3.connect(DB_PATH)
        return conn
    except Error as e: 
        print('Erreur connection : ', e)


def create_table(): 
    conn = create_connection()
    cur = conn.cursor()
    cur.execute("CREATE TABLE IF NOT EXISTS vulnerabilities ( id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT,impact TEXT, exploitation TEXT, risk TEXT )")

    conn.close()


def get_data():

    conn = create_connection()
    cur = conn.cursor()

    cur.execute("SELECT * FROM vulnerabilities")
    data_list = cur.fetchall()

    conn.commit()
    conn.close()

    return data_list

    

def add_data(data):
    conn = create_connection()
    cur = conn.cursor()

    cur.execute("INSERT INTO vulnerabilities (title,impact,exploitation,risk) VALUES (?,?,?,?)",(data["title"], data["impact"], data["exploitation"],data["risk"]))
    conn.commit()
    conn.close()
